### ISSUE TITLE
Does it have compatibility issues with macOS Sierra v10.12.1?

### ISSUE THREAD

**Issue by Roshanalexander** [networkprogrammer/bing-wallpaper-for-mac#12]
I followed your instructions to install your app but it doesn't seem like working. Have you tried it on the latest version of MacOS yet?

**Comment by networkprogrammer** [comment]
Unfortunately not yet. I'll take note of this, but do not think I'll have the time to update this anytime soon

**Comment by sahilanguralla** [comment]
Not working on Mac Sierra.

**Comment by Fofer** [comment]
I'm on macOS Sierra (10.12.3) and it's working fine for me, for what it's worth.

**Comment by j-gao** [comment]
How I made it work on my macOS Sierra (10.12.3):
To manually execute the program from terminal once:
`/Users/{user}/Applications/Bing Wallpaper/CheckBingStatus.app/Contents/MacOS/Application Stub`
The system will alert you about a failure due to unauthorized developer.
Then go to `System Preferences` -> `Security & Privacy` -> select `open anyway`, and you're good to go.
